# -*- coding: utf-8 -*-
"""I/O.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idZtxRFU_U5k__mok8iokxqbgMNgFDS3
"""

# MOSTRAR DADES AMB PRINT() I LLEGIR DADES AMB INPUT()
# ======================================================

# 1. EXEMPLE BÀSIC DE PRINT()
# ----------------------------
print("=== 1. Exemple bàsic ===")
print("Hola, món!")

print("\n" + "="*40 + "\n")

# 2. MOSTRAR TEXT I VARIABLES
# ----------------------------
print("=== 2. Mostrar text i variables ===")
name = "Anna"
age = 16
print("El teu nom és", name, "i tens", age, "anys.")
print(name, age)

print("\n" + "="*40 + "\n")

# 3. MOSTRAR VARIABLES CONCATENANT AMB +
# ---------------------------------------
print("=== 3. Concatenar amb + ===")
name = "Pau"
city = "Barcelona"
print("Em dic " + name + " i visc a " + city + ".")

print("\n" + "="*40 + "\n")

# 4. CONCATENAR NÚMEROS (AMB STR())
# ----------------------------------
print("=== 4. Concatenar números amb str() ===")
age = 18
print("Tinc " + str(age) + " anys.")

# ⚠️ Això donaria error:
# print("Tinc " + age + " anys.")  # ERROR: no es pot concatenar str amb int

print("\n" + "="*40 + "\n")

# 5. MOSTRAR TEXT AMB FORMAT (F-STRINGS)
# ---------------------------------------
print("=== 5. F-strings (forma moderna i recomanada) ===")
name = "Pol"
age = 17
print(f"Hola {name}, tens {age} anys.")

# Més exemples amb f-strings
city = "Girona"
temperature = 22.5
print(f"A {city} fa {temperature}°C")

print("\n" + "="*40 + "\n")

# 6. LLEGIR UN TEXT AMB INPUT()
# ------------------------------
print("=== 6. Llegir un text ===")
name = input("Com et dius? ")
print(f"Encantat de conèixer-te, {name}!")

print("\n" + "="*40 + "\n")

# 7. LLEGIR UN NÚMERO ENTER
# --------------------------
print("=== 7. Llegir un número enter ===")
age = int(input("Quants anys tens? "))
print(f"L'any vinent tindràs {age + 1} anys.")

print("\n" + "="*40 + "\n")

# 8. LLEGIR UN NÚMERO DECIMAL
# ----------------------------
print("=== 8. Llegir un número decimal ===")
height = float(input("Escriu la teva alçada en metres: "))
print(f"La teva alçada és {height} m.")

print("\n" + "="*40 + "\n")

# 9. EXEMPLE COMPLET
# ------------------
print("=== 9. Exemple complet ===")
name = input("Nom: ")
age = int(input("Edat: "))
height = float(input("Alçada (m): "))

print(f"Et dius {name}, tens {age} anys i fas {height} metres d'alçada.")

print("\n" + "="*40 + "\n")

# 10. EXEMPLE PRÀCTIC: CALCULADORA SIMPLE
# ----------------------------------------
print("=== 10. Calculadora simple ===")
num1 = float(input("Introdueix el primer número: "))
num2 = float(input("Introdueix el segon número: "))

suma = num1 + num2
resta = num1 - num2
multiplicacio = num1 * num2
divisio = num1 / num2

print(f"\nResultats:")
print(f"{num1} + {num2} = {suma}")
print(f"{num1} - {num2} = {resta}")
print(f"{num1} * {num2} = {multiplicacio}")
print(f"{num1} / {num2} = {divisio}")

print("\n" + "="*40 + "\n")

# 11. EXEMPLE PRÀCTIC: CONVERTIDOR DE TEMPERATURES
# -------------------------------------------------
print("=== 11. Convertidor Celsius a Fahrenheit ===")
celsius = float(input("Temperatura en Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print(f"{celsius}°C equivalen a {fahrenheit}°F")

print("\n" + "="*40 + "\n")

# 12. EXEMPLE PRÀCTIC: CÀLCUL D'ÀREA D'UN RECTANGLE
# --------------------------------------------------
print("=== 12. Càlcul d'àrea d'un rectangle ===")
base = float(input("Base del rectangle (cm): "))
altura = float(input("Altura del rectangle (cm): "))
area = base * altura
perimetre = 2 * (base + altura)

print(f"\nÀrea: {area} cm²")
print(f"Perímetre: {perimetre} cm")

print("\n" + "="*40 + "\n")

# 13. EXEMPLE PRÀCTIC: INFORMACIÓ PERSONAL
# -----------------------------------------
print("=== 13. Qüestionari personal ===")
nom = input("Quin és el teu nom? ")
cognom = input("Quin és el teu cognom? ")
edat = int(input("Quina edat tens? "))
ciutat = input("On vius? ")
aficio = input("Quina és la teva afició favorita? ")

print(f"\n--- Resum ---")
print(f"Nom complet: {nom} {cognom}")
print(f"Edat: {edat} anys")
print(f"Ciutat: {ciutat}")
print(f"Afició: {aficio}")

print("\n" + "="*40 + "\n")

# 14. EXEMPLE AMB MÚLTIPLES F-STRINGS
# ------------------------------------
print("=== 14. F-strings amb operacions ===")
preu = float(input("Preu del producte (€): "))
quantitat = int(input("Quantitat: "))
descompte = float(input("Descompte (%): "))

subtotal = preu * quantitat
import_descompte = subtotal * (descompte / 100)
total = subtotal - import_descompte

print(f"\nSubtotal: {subtotal:.2f}€")
print(f"Descompte ({descompte}%): -{import_descompte:.2f}€")
print(f"Total a pagar: {total:.2f}€")

print("\n" + "="*40 + "\n")

# 15. COMPARACIÓ DE MÈTODES DE PRINT()
# -------------------------------------
print("=== 15. Comparació de mètodes ===")
nom = "Maria"
edat = 20

# Mètode 1: Separació automàtica amb comes
print("Mètode 1:", nom, edat)

# Mètode 2: Concatenació amb +
print("Mètode 2: " + nom + " " + str(edat))

# Mètode 3: F-strings (recomanat)
print(f"Mètode 3: {nom} {edat}")

print("\n" + "="*40 + "\n")
print("FI DEL PROGRAMA")